### ISSUE TITLE
Javascript ignore files doesn't actually ignore the files

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#4]
i've added ` app/assets/javascripts/dd_belatedpng.js ` to the ignores on https://awesomecode.io/projects/58  many times

![image](https://user-images.githubusercontent.com/12266/45064924-9c028400-b10a-11e8-8daf-9b5ef17bf18e.png)

and i've added `public/api/docs/app.js` to https://awesomecode.io/projects/93
![image](https://user-images.githubusercontent.com/12266/45064955-c81e0500-b10a-11e8-925d-bf362d1a0e55.png)

But in both projects, awesomecode.io keeps finding javascript things it wants to correct in these files

**Comment by flyerhzm** [comment]
@Br3nda Sorry for the inconvenient, it's caused by upgrading dependent eslint. We have fixed it, please try rebuild and let us know if it's working for you.

**Comment by Br3nda** [comment]
This is still happening. The javascript files in my ignores are still getting PRs
e.g.
https://github.com/WhareHauora/wharehauora-server/pull/543/files

**Comment by flyerhzm** [comment]
@Br3nda I'm on holiday, I will try to fix it ASAP when I'm back.

**Comment by flyerhzm** [comment]
@Br3nda sorry for the late, but we have fixed the issue, please try again

**Comment by Br3nda** [comment]
Fixed
